#!/bin/bash

set -eu
topdir=/opt/jd-gui

jarfile=jd-gui.jar
if [ ! -r "$topdir/$jarfile" ]
then
    echo $(basename "$0")": can't find $jarfile under '$topdir'."
    exit 1
fi

JAVA_OPTS="${JAVA_OPTS:--Xmx512M -Dfile.encoding=utf-8}"

exec java $JAVA_OPTS -jar "$topdir/$jarfile" "$@"
